#Port Setting
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 5024MB

#JSP Setting
spring:
    
#mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PW}

#파일사이즈
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB

  #(email)
  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: gim28711@gmail.com #앱 비밀번호 발급받은 google 계정
    password: ${GMAIL_SECRET} #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  OAuth2:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 971637697594-68bcvkhk30hcm3nfitdr9q0vofjagm54.apps.googleusercontent.com
            client-secret: ${GOOGLE_SECRET}
            scope:
            - profile
            - email
          kakao:
            client-name: kakao
            client-id: 746dd0b3d390eeffc122a0f59031a86d
            client-secret: ${KAKAO_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "http://bitplanner.store/login/oauth2/code/kakao"
            client-authentication-method: POST 
            scope:
            - profile_nickname
            - profile_image
            - account_email
          naver:
            client-name: naver
            client-id: hmyfMJqTioV4b2qO9JUH # 앱키 -> REST API 키
            client-secret: ${NAVER_SECRET} # 네이버 로그인 -> 보안 -> Client Secret 코드
            authorization-grant-type: authorization_code
            redirect-uri: "http://bitplanner.store/login/oauth2/code/naver" # yml 파일에서 {} 가 spring 특수문자로 인식되게 하기 위해 " " 사용
            scope:
            - name
            - email
            - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # "인가 코드 받기" 항목
            token-uri: https://nid.naver.com/oauth2.0/token # "토큰 받기" 항목
            user-info-uri: https://openapi.naver.com/v1/nid/me # "사용자 정보 가져오기" 항목
            user-name-attribute: response # 식별자 . 카카오의 경우 "id" 사용
#Mybatis Setting
mybatis:
  type-aliases-package: data.dto
  mapper-locations: /mapper/**/*.xml